apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-claim
    namespace: shopping
spec:
    resources:
      requests:
        storage: 2Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: ""
    volumeName: pv-volume
