apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: shopping
  name: shopping-deploy-v1
  namespace: shopping
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: shopping
      version: "v1.0"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shopping
        version: "v1.0"
    spec:
      containers:
      - image: manningkubernetes/shopping-p4:1.0
        name: shopping
        env:
        - name: USERNAME 
          valueFrom:
            secretKeyRef:
              name: shopping-credentials
              key: username 
        - name: PASSWORD 
          valueFrom:
            secretKeyRef:
              name: shopping-credentials
              key: password 
        resources: {}
status: {}
